### ISSUE TITLE
Versions problem

### ISSUE THREAD

**Issue by BurakOgutken** [BitzArt/OCPI.Net#10]
hello, I wanted to try a web service with your library, but I am getting the following error, what could be the reason?

Thank you

Can not parse 'Receiver' to enum 'InterfaceRole'

**Comment by YuriyDurov** [comment]
Hello @BurakOgutken,

It appears that the issue you're encountering might be related to the absence of the enum-to-string Json converter. This package relies on the [EnumMember] attribute to define string representations for enum values. You can refer to the enums' definitions in this [link](https://github.com/BitzArt/OCPI.Net/blob/main/src/OCPI.Net.Core/Enums/Versioning/InterfaceRole.cs) to get a better understanding.

To resolve this, ensure that you have configured your JSON serializer as demonstrated in this [example](https://github.com/BitzArt/OCPI.Net/blob/main/src/OCPI.Net.Controllers/Extensions/ConfigureOcpiJsonExtension.cs). You might be missing the following line:
```
SerializerOptions.Converters.Add(new JsonStringEnumMemberConverter());
```

If you're still encountering issues, kindly provide more details about your problem, and we'll do our best to assist you further in resolving it.

**Comment by BurakOgutken** [comment]
Hi again

I tried to use it as in your sample application and got exactly the same code.

` [Route("versions")]
 public class VersionsController : OcpiController
 {
     readonly IOcpiVersionService _versionService;

     public VersionsController(IOcpiVersionService versionService) {
         _versionService = versionService;
     }

     [HttpGet]
     public IActionResult GetVersionsAsync()
     {
         var versionInfo = _versionService.GetVersions();
         return OcpiOk(versionInfo);
     }

     [HttpGet("{request}")]
     public IActionResult GetVersionDetailsAsync([FromRoute] string request)
     {
         var details = _versionService.GetVersionDetails(request);
         return OcpiOk(details);
     }
 }`

When I call with postman I directly get this error

`{
    "status_code": 3000,
    "status_message": "Server error",
    "timestamp": "2023-09-10T23:19:09.820Z",
    "problem": {
        "title": "Can not parse 'Receiver' to enum 'InterfaceRole'"
    }
}`

**Comment by YuriyDurov** [comment]
Hello once more, @BurakOgutken,

The sample application is functional, serving as a reference for your needs. Feel free to run the sample WebApi to gain a better understanding of how the package is supposed to operate.

The encountered issue appears to be associated with the JsonSerializer. It's worth noting that the package utilizes the built-in DI Container to retain JsonSerializer configurations. Are you certain that you are not inadvertently overwriting JsonSerializerOptions subsequent to executing `builder.AddOcpi();`?

Should none of the above suggestions resolve the issue, kindly provide a sample repository where the same problem can be replicated. This will facilitate a more in-depth investigation.

**Comment by BurakOgutken** [comment]
greetings again,

I used your application exactly but the same problem persists.

**Comment by YuriyDurov** [comment]
You are supposed to be able to call the versions OCPI module using the '/versions' endpoint of the sample WebApi.

We are unable to replicate on our end the issue that you are getting.
Please attach a sample solution that would replicate it for us to be able to track the issue down.

**Comment by YuriyDurov** [comment]
Hello again @BurakOgutken, I am closing this issue for now, but please don't hesitate to re-open it in the future if you have more details to add to this.

**Comment by BurakOgutken** [comment]
hi again

My problem is still ongoing. I am experiencing the same issue even with your standard test project. I am using Postman to make a request to the http://localhost/versions endpoint and I receive the following error. It seems like I am using something incorrectly. How should I properly use it?

`{
    "status_code": 3000,
    "status_message": "Server error",
    "timestamp": "2023-11-20T07:05:00.765Z",
    "problem": {
        "title": "Cannot parse 'Receiver' to enum 'InterfaceRole'"
    }
}`

**Comment by YuriyDurov** [comment]
Hello @BurakOgutken, I have checked the sample project in this repository and I am unable to replicate the problem there.

Please attach a sample solution where this issue can be replicated in order for us to be able to attempt fixing it.
