### ISSUE TITLE
Country code serialization strings values are lower case

### ISSUE THREAD

**Issue by LiorBenAri** [BitzArt/OCPI.Net#19]
Hi,
The Country Code serialization strings values that are defined on the library are of lower case.
https://github.com/BitzArt/OCPI.Net/blob/80f189a3727fdc64187fb6749e78d0134e55266e/src/OCPI.Net.Core/Enums/!General/CountryCode.cs#L5

From what I see on the OCPI protocol (version 2.2.1), the Country Code values should be formatted according to the ISO-3166 alpha-2 protocol:  
![image](https://github.com/BitzArt/OCPI.Net/assets/23519630/86d33f17-5b6a-42fa-9dd4-4f539039518f)
https://en.wikipedia.org/wiki/List_of_ISO_3166_country_codes
Meaning, Country Codes values should of upper case.

WDYT?
Did other clients of the library also raised this issue?
Currently, it's a problem for us to use the library OCPI modules objects, since the OCPI parties we are interacting with don't accept the lower case Country Codes.

Would be happy to hear your feedback regarding this.

Thanks,
Lior

**Comment by YuriyDurov** [comment]
@LiorBenAri This is true. Fixed in a new version 0.14.2. Pls let me know if this resolves the issue.

**Comment by LiorBenAri** [comment]
issue resolved, thank you @YuriyDurov!
