### ISSUE TITLE
HTTP response code from ApiException ?

### ISSUE THREAD

**Issue by duke-bartholomew** [BitzArt/OCPI.Net#28]
In your CredentialsController example you have the placeholder: `if (platform.IsRegistered == false) throw ApiException.MethodNotAllowed`.

But as far as I can tell, the `ApiException.MethodNotAllowed` exception will result in a HTTP 200OK with OCPI status 'error' in it.
According to the OCPI spec, the result here should be a `HTTP 405 MethodNotAllowed`.

Is there any way to define the HTTP response-codes inside the `ApiException` so that they get properly mapped to HTTP response codes?

**Comment by YuriyDurov** [comment]
Hello @duke-bartholomew 

Try `OcpiException` static class

E.g. `throw OcpiException.Custom()`
